name = "ecoulson-cloudflare-app"
type = "webpack"
account_id = "wrangler generate my-app https://github.com/cloudflare/worker-sites-template"
workers_dev = true
route = ""
zone_id = ""
webpack_config = "webpack.config.js"
